name: Generate Helm Docs

on:
  pull_request:
    branches:
      - '*'  # Run on all pull requests

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Generate Helm Docs
        uses: losisin/helm-docs-github-action@v1.3.1
        with:
          chart-search-root: "charts/magistrala"
          values-file: "values.yaml"
          output-file: "README.md"
          template-files: "README.md.gotmpl"
          git-push: false
          fail-on-diff: false

      # Show the output of the README.md file after it's generated
      - name: Show README.md content
        run: cat charts/magistrala/README.md

      # Show the diff between the current README and the generated one (if fail-on-diff: true fails)
      - name: Show README diff
        run: git diff charts/magistrala/README.md
