name: Generate Helm Docs

on:
  pull_request:
    branches:
      - MG-143

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Generate Helm Docs
        uses: losisin/helm-docs-github-action@v1.3.1
        with:
          chart-search-root: "charts/magistrala"
          values-file: "values.yaml"
          output-file: "README.md"
          template-files: "README.md.gotmpl"
          git-push: true
          git-push-user-name: "github-actions[bot]"
          git-push-user-email: "github-actions[bot]@users.noreply.github.com"
          git-commit-message: "Auto-generate Helm chart documentation"
          fail-on-diff: true
